# Site settings
name: Dentysta Irlandia
title: Dentysta Irlandia
email: iza@dentysta-irlandia.eu
description: "Lorem ipsum dolor, sit amet"
baseurl: ""
url: "http://localhost:4000"
author: "annonymous"

# Build settings
markdown: kramdown
permalinks: pretty
