# Site settings
name: Dentysta Irlandia
title: Dentysta Irlandia
email: iza@dentysta-irlandia.eu
description: "Dentysta Irlandia"
baseurl: ""
url: "http://dentysta-irlandia.eu"
author: "Agile Sparkle"

# Build settings
markdown: kramdown
permalinks: pretty

# Deploy
ftp_host: 'serwer1405607.home.pl'
ftp_dir: '/dentysta-irlandia.eu'
ftp_passive: false

ftp_port: 21


